### PR TITLE
Complete migration

### PR DESCRIPTION
**Pull request by Lucashuang0802**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts. Confirmation: @Lucashuang0802
## What's in this pull request?

> We migrate our screen-sharing accelerator pack core code to a new repo: https://github.com/opentok/screen-sharing-acc-pack and keep sample app here.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/screensharing-annotation-acc-pack/pull/97" target="_blank">ReviewNinja

**Comment by Lucashuang0802** [comment]
**WAIT UNTIL QA SIGNOFF**

**Comment by Lucashuang0802** [comment]
👍

**Comment by marinaserranomontes** [comment]
LGTM

**Pull request merged**
